# yaml-language-server: $schema=https://raw.githubusercontent.com/rhombusgg/rhombus-rs/main/schema.json
title: Rhombus Demo
location_url: http://localhost:3000
database_url: file://rhombus.db
contact_email: admin@rhombus.gg
in_memory_cache: 20
# uploads:
#   s3:
#     bucket_name: my-test-bucket
#     access_key: VfpJaZlunFoqBkij08se
#     endpoint: http://localhost:9000
#     path_style: true
auth:
  - discord
  - email
  - credentials
divisions:
  - name: Open
    description: Open division for everyone
  - name: Undergraduate
    description: Undergraduate university students globally
    email_regex: ^.*.edu$
    requirement: Must verify a valid university .edu email address. Max of up to 4 players
    max_players: 4
  - name: OSU
    description: OSU undergraduate students
    email_regex: ^.*\.\d+@(buckeyemail\.)?osu\.edu$
    requirement: Must verify a valid OSU email address
    max_players: 1
ctftime:
  client_id: 1
discord:
  guild_id: 1160610137703186636
  client_id: 1160076447977848945
#   author_role_id: 1198496803130183770
#   first_blood_channel_id: 1240422645938389102
  support_channel_id: 1173026578385617010
#   verified_role_id: 1170429782270431283
