# yaml-language-server: $schema=https://raw.githubusercontent.com/rhombusgg/rhombus/main/schema.json
location_url: http://localhost:3000
contact_email: demo@rhombus.gg
database_url: file://rhombus.db
start_time: 2024-09-04T03:14:00Z
uploads:
  local:
    folder: uploads
auth:
  - discord
  - email
  - credentials
divisions:
  - name: Open
    description: Open division for everyone
  - name: Undergraduate
    description: Undergraduate university students globally
    email_regex: ^.*.edu$
    requirement: Must verify a valid university .edu email address. Max of up to 4 players
    max_players: 4
discord:
  guild_id: 1160610137703186636
  client_id: 1160076447977848945
  author_role_id: 1198496803130183770
  # first_blood_channel_id: 1240422645938389102
  support_channel_id: 1173026578385617010
  verified_role_id: 1170429782270431283
ctftime:
  client_id: 2449
title: Rhombus Demo
description: A fully featured demo instance of the Rhombus CTF platform.
organizer: Team Rhombus
home:
  content: |
    # Welcome to the Rhombus Demo

    This is a demo instance of [Rhombus](https://github.com/rhombusgg/rhombus). Feel free to _explore_ the platform and create challenges.

    - It resets every 10 minutes.
    - You can make yourself an admin by going to [your account](/account).
